"use client";

import React, { useRef, useState } from "react";
import { useOperationalIntelligence } from "@/context/OperationalIntelligenceContext";
import {
  FileText,
  Printer,
  Download,
  X,
  CheckCircle2,
  AlertTriangle,
  Radio,
  MapPin,
  Calendar,
  Layers,
  ShieldCheck,
  Zap,
  Truck,
  Building2,
  Thermometer,
} from "lucide-react";

import { useStation } from "@/context/StationContext";
import { generateMissionReportPdf } from "@/lib/pdfReportGenerator";

interface MissionReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const MissionReportModal: React.FC<MissionReportModalProps> = ({ isOpen, onClose }) => {
  const {
    missionReport,
    missionReadiness,
    maintenanceRecords,
    scenarioTimeline,
    interStationCoordination,
    currentRoute,
    communicationHealth,
    cascadeResult,
    resources,
    isSimulationActive,
  } = useOperationalIntelligence();
  const { selectedStation } = useStation();
  const [isExporting, setIsExporting] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    const reportText = `========================================================
MISSION INTELLIGENCE REPORT — INDIAN ANTARCTIC PROGRAMME
========================================================
Station: ${missionReport.stationName} (${missionReport.coordinates})
Timestamp: ${missionReport.timestampUtc}
Generated By: ${missionReport.generatedBy}

--------------------------------------------------------
1. MISSION READINESS & STATION HEALTH
--------------------------------------------------------
Mission Readiness Score: ${missionReport.healthScore}%
Readiness Status: ${missionReport.readinessStatus}
Readiness Impact Delta: ${missionReport.readinessDelta > 0 ? "+" : ""}${missionReport.readinessDelta} pts
Environment: ${missionReport.environmentStatus}
Energy: ${missionReport.energyStatus}
Infrastructure: ${missionReport.infrastructureStatus}
Logistics: ${missionReport.logisticsStatus}
Communication: ${missionReport.communicationStatus} (${missionReport.communicationScore}%, ${missionReport.communicationLatencyMs}ms latency)

--------------------------------------------------------
2. ENVIRONMENT
--------------------------------------------------------
Temperature: ${missionReport.temperatureC}°C
Wind Speed: ${missionReport.windSpeedMs} m/s
Pressure: ${missionReport.pressureHpa} hPa
Snow / Atmosphere: ${missionReport.snowState}

--------------------------------------------------------
3. ENERGY
--------------------------------------------------------
Battery SOC: ${missionReport.batterySocPct}%
Generator Status: ${missionReport.generatorStatus}
Power Consumption: ${missionReport.powerConsumptionKw} kW
Power Generation: ${missionReport.powerGenerationKw} kW
Net Power Balance: ${missionReport.netPowerKw} kW
Fuel Level: ${missionReport.fuelLevelPct}%
Estimated Endurance: ${missionReport.estimatedEnduranceHours} hours

--------------------------------------------------------
4. INFRASTRUCTURE & PREDICTIVE MAINTENANCE
--------------------------------------------------------
Critical Systems: ${missionReport.criticalSystemsStatus}
Equipment Health: ${missionReport.equipmentHealthPct}%
Maintenance Summary: ${missionReport.maintenancePrioritySummary}
Detected Failures:
${missionReport.detectedFailures.map((f) => ` - ${f}`).join("\n")}
Maintenance Priority Queue:
${missionReport.maintenanceRisks.map((m) => ` - ${m}`).join("\n")}

--------------------------------------------------------
5. LOGISTICS
--------------------------------------------------------
Fuel Autonomy: ${missionReport.fuelAutonomyDays} days
Food Reserves: ${missionReport.foodReservesDays} days
Water Reserves: ${missionReport.waterReservesDays} days
Medical Supplies: ${missionReport.medicalSuppliesStatus}
Resupply Status: ${missionReport.resupplyStatus}

--------------------------------------------------------
6. ACTIVE RISKS
--------------------------------------------------------
${missionReport.activeRisks.map((r) => `${r.rank}. ${r.title} [${r.severity}] — ${r.timeToCritical}`).join("\n")}

--------------------------------------------------------
7. FORECAST
--------------------------------------------------------
${missionReport.forecastHighlights.map((fh) => ` - ${fh}`).join("\n")}

--------------------------------------------------------
8. WHAT-IF SCENARIO
--------------------------------------------------------
Scenario: ${missionReport.whatIfScenarioTitle}
Duration: ${missionReport.whatIfDuration}
Overall Risk: ${missionReport.whatIfOverallRisk}
Time to Critical: ${missionReport.whatIfTimeUntilCritical}

--------------------------------------------------------
9. CASCADING IMPACT CHAIN
--------------------------------------------------------
${missionReport.cascadingChain.map((c) => `Step ${c.step} [${c.system}]: ${c.label} (${c.detail})`).join("\n ↓ \n")}

--------------------------------------------------------
10. RECOMMENDED ACTIONS
--------------------------------------------------------
${missionReport.recommendedActions.map((a) => ` - [${a.status}] ${a.action}: ${a.impact}`).join("\n")}
========================================================`;

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Mission_Report_${missionReport.station}_${new Date().toISOString().slice(0, 10)}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = () => {
    try {
      setIsExporting(true);
      generateMissionReportPdf({
        missionReport,
        missionReadiness,
        maintenanceRecords,
        scenarioTimeline,
        interStationCoordination,
        currentRoute,
        communicationHealth,
        cascadeResult,
        resources,
        isSimulationActive,
        stationId: selectedStation,
      });
    } catch (err) {
      console.error("PDF generation failed, falling back to text export:", err);
      handleDownloadText();
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/75 backdrop-blur-md overflow-y-auto">
      <div className="relative w-full max-w-4xl max-h-[92vh] flex flex-col rounded-[28px] border border-white/10 bg-ops-panel shadow-[0_25px_70px_rgba(0,0,0,0.7)] overflow-hidden">
        {/* Top Action Bar (hidden in print) */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-ops-card/70 print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-ops-teal/15 text-ops-teal border border-ops-teal/30 flex items-center justify-center">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold text-white">
                  Mission Intelligence Executive Briefing
                </span>
                <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-ops-teal/20 text-ops-teal border border-ops-teal/30 uppercase">
                  {missionReport.station}
                </span>
              </div>
              <p className="text-[11px] text-ops-text-3">
                Polar Scientific Digital Twin · 10-Section Synthesis
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-ops-card hover:bg-white/10 border border-white/10 text-xs font-semibold text-ops-text transition-colors cursor-pointer"
              title="Print clean briefing view"
            >
              <Printer className="w-4 h-4 text-ops-teal" />
              <span>Print Briefing</span>
            </button>

            <button
              type="button"
              onClick={handleExportPdf}
              disabled={isExporting}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-ops-card hover:bg-white/10 border border-white/10 text-xs font-semibold text-ops-text transition-colors cursor-pointer disabled:opacity-50"
              title="Download professional PDF report"
            >
              <Download className="w-4 h-4 text-ops-amber" />
              <span>{isExporting ? "Generating..." : "Export PDF"}</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-2 rounded-xl text-ops-text-2 hover:text-white hover:bg-white/10 transition-colors ml-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Scrollable Report Content */}
        <div
          ref={reportRef}
          className="flex-1 overflow-y-auto p-6 sm:p-9 space-y-7 text-ops-text bg-ops-bg/95 font-sans print:p-0 print:bg-white print:text-black"
        >
          {/* Header Strip */}
          <div className="pb-6 border-b border-white/10 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="w-2 h-2 rounded-full bg-ops-teal" />
                <span className="text-[10px] font-bold uppercase tracking-[0.18em] text-ops-teal">
                  INDIAN ANTARCTIC PROGRAMME · NCPOR / MoES
                </span>
              </div>
              <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white print:text-black">
                {missionReport.stationName}
              </h1>
              <div className="flex flex-wrap items-center gap-3 mt-1.5 text-xs text-ops-text-3">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3.5 h-3.5 text-ops-teal" />
                  {missionReport.coordinates}
                </span>
                <span>•</span>
                <span>{missionReport.region}</span>
              </div>
            </div>

            <div className="text-right text-xs text-ops-text-3">
              <div className="font-semibold text-ops-text print:text-black tabular-nums">
                {missionReport.timestampUtc}
              </div>
              <div className="text-[10px] text-ops-teal mt-0.5">
                Scientific Digital Twin v0.1.0
              </div>
            </div>
          </div>

          {/* 1. STATION HEALTH & MISSION READINESS */}
          <section className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
                <span>01</span>
                <span>Mission Readiness &amp; Subsystem Health</span>
              </h2>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase bg-ops-teal/15 text-ops-teal border border-ops-teal/30">
                  {missionReport.readinessStatus}
                </span>
                {missionReport.readinessDelta !== 0 && (
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                    missionReport.readinessDelta > 0
                      ? "bg-ops-green/15 text-ops-green border border-ops-green/30"
                      : "bg-ops-red/15 text-ops-red border border-ops-red/30"
                  }`}>
                    {missionReport.readinessDelta > 0 ? `+${missionReport.readinessDelta}` : missionReport.readinessDelta} pts
                  </span>
                )}
              </div>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-6 gap-3">
              <div className="p-3.5 rounded-xl bg-ops-card border border-white/10">
                <div className="text-[10px] uppercase font-bold text-ops-text-3">Readiness Score</div>
                <div className="text-2xl font-extrabold text-white mt-1 tabular-nums">
                  {missionReport.healthScore}%
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-ops-card border border-white/10">
                <div className="text-[10px] uppercase font-bold text-ops-text-3">Environment</div>
                <div className="text-sm font-bold text-ops-green mt-2">
                  {missionReport.environmentStatus}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-ops-card border border-white/10">
                <div className="text-[10px] uppercase font-bold text-ops-text-3">Energy</div>
                <div className="text-sm font-bold text-ops-amber mt-2">
                  {missionReport.energyStatus}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-ops-card border border-white/10">
                <div className="text-[10px] uppercase font-bold text-ops-text-3">Infrastructure</div>
                <div className="text-sm font-bold text-ops-teal mt-2">
                  {missionReport.infrastructureStatus}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-ops-card border border-white/10">
                <div className="text-[10px] uppercase font-bold text-ops-text-3">Logistics</div>
                <div className="text-sm font-bold text-ops-red mt-2">
                  {missionReport.logisticsStatus}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-ops-card border border-white/10">
                <div className="text-[10px] uppercase font-bold text-ops-text-3">Comms Link</div>
                <div className={`text-sm font-bold mt-2 ${
                  missionReport.communicationStatus === "CONNECTED"
                    ? "text-ops-green"
                    : missionReport.communicationStatus === "DEGRADED"
                    ? "text-ops-amber"
                    : "text-ops-red"
                }`}>
                  {missionReport.communicationStatus}
                </div>
              </div>
            </div>
          </section>

          {/* 2. ENVIRONMENT */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>02</span>
              <span>Observed Meteorological Conditions</span>
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Temperature</span>
                <p className="text-base font-bold text-white mt-1 tabular-nums">
                  {missionReport.temperatureC}°C
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Wind Speed</span>
                <p className="text-base font-bold text-white mt-1 tabular-nums">
                  {missionReport.windSpeedMs} m/s
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Pressure</span>
                <p className="text-base font-bold text-white mt-1 tabular-nums">
                  {missionReport.pressureHpa} hPa
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Snow / State</span>
                <p className="text-xs font-bold text-white mt-1">
                  {missionReport.snowState}
                </p>
              </div>
            </div>
          </section>

          {/* 3. ENERGY */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>03</span>
              <span>Power Microgrid &amp; Fuel Generation</span>
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Battery SOC</span>
                <p className="text-base font-bold text-ops-amber mt-1 tabular-nums">
                  {missionReport.batterySocPct}%
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Estimated Endurance</span>
                <p className="text-base font-bold text-ops-red mt-1 tabular-nums">
                  {missionReport.estimatedEnduranceHours} hours
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Load / Gen</span>
                <p className="text-base font-bold text-white mt-1 tabular-nums">
                  {missionReport.powerConsumptionKw} / {missionReport.powerGenerationKw} kW
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Diesel Level</span>
                <p className="text-base font-bold text-ops-teal mt-1 tabular-nums">
                  {missionReport.fuelLevelPct}%
                </p>
              </div>
            </div>
          </section>

          {/* 4. INFRASTRUCTURE */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>04</span>
              <span>Physical Infrastructure &amp; Equipment Health</span>
            </h2>
            <div className="p-4 rounded-xl bg-ops-card/60 border border-white/5 space-y-2 text-xs">
              <div className="flex items-center justify-between">
                <span className="text-ops-text-3">Critical Systems Status:</span>
                <span className="font-semibold text-white">{missionReport.criticalSystemsStatus}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-ops-text-3">Predictive Maintenance Priority:</span>
                <span className="font-semibold text-ops-amber">{missionReport.maintenancePrioritySummary}</span>
              </div>
              <div className="pt-2 border-t border-white/5">
                <span className="text-[10px] font-bold uppercase text-ops-text-3">Detected Mechanical Warnings:</span>
                <ul className="mt-1 space-y-1 list-disc list-inside text-ops-text-2">
                  {missionReport.detectedFailures.map((df, i) => (
                    <li key={i}>{df}</li>
                  ))}
                </ul>
              </div>
              <div className="pt-2 border-t border-white/5">
                <span className="text-[10px] font-bold uppercase text-ops-text-3">Predictive Maintenance Queue:</span>
                <ul className="mt-1 space-y-1 list-disc list-inside text-ops-text-2">
                  {missionReport.maintenanceRisks.map((mr, i) => (
                    <li key={i} className="text-ops-amber/90">{mr}</li>
                  ))}
                </ul>
              </div>
            </div>
          </section>

          {/* 5. LOGISTICS */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>05</span>
              <span>Logistics Reserves &amp; Resupply Status</span>
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Fuel Autonomy</span>
                <p className="text-base font-bold text-ops-amber mt-1 tabular-nums">
                  {missionReport.fuelAutonomyDays} days
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Food Reserves</span>
                <p className="text-base font-bold text-white mt-1 tabular-nums">
                  {missionReport.foodReservesDays} days
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Potable Water</span>
                <p className="text-base font-bold text-white mt-1 tabular-nums">
                  {missionReport.waterReservesDays} days
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Medical Tier</span>
                <p className="text-xs font-bold text-ops-green mt-1">
                  100% Certified
                </p>
              </div>
            </div>
          </section>

          {/* 6. ACTIVE RISKS */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>06</span>
              <span>High-Priority Active Operational Risks</span>
            </h2>
            <div className="space-y-2">
              {missionReport.activeRisks.map((risk) => (
                <div
                  key={risk.rank}
                  className="flex items-center justify-between p-3 rounded-xl bg-ops-card/60 border border-white/5 text-xs"
                >
                  <div className="flex items-center gap-3">
                    <span className="w-5 h-5 rounded-md bg-ops-panel border border-white/10 flex items-center justify-center font-bold text-ops-text">
                      {risk.rank}
                    </span>
                    <span className="font-semibold text-white">{risk.title}</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-ops-text-3 text-[11px] tabular-nums">
                      {risk.timeToCritical}
                    </span>
                    <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-ops-red/20 text-ops-red border border-ops-red/30">
                      {risk.severity}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 7. FORECAST */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>07</span>
              <span>Projected Depletion Horizon Summary</span>
            </h2>
            <ul className="space-y-2 text-xs text-ops-text-2 bg-ops-card/60 p-4 rounded-xl border border-white/5">
              {missionReport.forecastHighlights.map((f, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-ops-teal mt-0.5">▪</span>
                  <span>{f}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* 8. WHAT-IF SCENARIO */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>08</span>
              <span>Active What-If Disruption Scenario</span>
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Active Scenario</span>
                <p className="text-xs font-bold text-white mt-1">
                  {missionReport.whatIfScenarioTitle}
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Duration Window</span>
                <p className="text-xs font-bold text-white mt-1">
                  {missionReport.whatIfDuration}
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Overall Risk</span>
                <p className="text-xs font-bold text-ops-red mt-1">
                  {missionReport.whatIfOverallRisk}
                </p>
              </div>
              <div className="p-3 rounded-xl bg-ops-card/60 border border-white/5">
                <span className="text-[10px] text-ops-text-3 uppercase font-semibold">Time to Critical</span>
                <p className="text-xs font-bold text-ops-amber mt-1">
                  {missionReport.whatIfTimeUntilCritical}
                </p>
              </div>
            </div>
          </section>

          {/* 9. CASCADING IMPACT */}
          <section className="space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>09</span>
              <span>Cascading Impact Chain Sequence</span>
            </h2>
            <div className="space-y-2">
              {missionReport.cascadingChain.map((step) => (
                <div
                  key={step.step}
                  className="flex items-start gap-3 p-3 rounded-xl bg-ops-card/40 border border-white/5 text-xs"
                >
                  <span className="w-5 h-5 rounded-full bg-ops-panel border border-white/10 flex items-center justify-center text-[10px] font-bold text-ops-teal shrink-0">
                    {step.step}
                  </span>
                  <div>
                    <div className="font-bold text-white">{step.label}</div>
                    <div className="text-[11px] text-ops-text-2 mt-0.5">{step.detail}</div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 10. RECOMMENDED ACTIONS */}
          <section className="space-y-3 pb-4">
            <h2 className="text-xs font-bold uppercase tracking-[0.16em] text-ops-teal flex items-center gap-2">
              <span>10</span>
              <span>Recommended Operational Mitigation Actions</span>
            </h2>
            <div className="space-y-2">
              {missionReport.recommendedActions.map((action, idx) => (
                <div
                  key={action.id}
                  className="flex items-start justify-between gap-3 p-3.5 rounded-xl bg-ops-card/70 border border-ops-green/20 text-xs"
                >
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-white">{action.action}</span>
                      <span className="px-2 py-0.5 rounded text-[8px] font-bold bg-ops-green/15 text-ops-green border border-ops-green/30">
                        {action.status}
                      </span>
                    </div>
                    <p className="text-[11px] text-ops-text-2 mt-1">{action.impact}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};
